/**
 * Canonical Feature Keys for SiDaya Platform
 * Used for dynamic tenant entitlement checks, subscription tier gating,
 * and modular runtime activation/deactivation.
 */
export enum FeatureKey {
  // Core Essentials (Starter Tier)
  CORE_POS = 'CORE_POS',
  BASIC_INVENTORY = 'BASIC_INVENTORY',
  RECEIPT_PRINTING_THERMAL = 'RECEIPT_PRINTING_THERMAL',
  CLIENT_PAYLINK = 'CLIENT_PAYLINK',

  // B2B Wholesale & Logistics (Grosir Pro Tier)
  WHOLESALE_PRICING = 'WHOLESALE_PRICING',
  COMPOUND_DISCOUNTS = 'COMPOUND_DISCOUNTS',
  UNIT_CONVERSIONS = 'UNIT_CONVERSIONS',
  CUSTOMER_TIERS = 'CUSTOMER_TIERS',
  INBOUND_PROCUREMENT = 'INBOUND_PROCUREMENT',
  STORAGE_BINS = 'STORAGE_BINS',
  FIFO_BATCH_ALLOCATION = 'FIFO_BATCH_ALLOCATION',
  DRIVER_SURAT_JALAN = 'DRIVER_SURAT_JALAN',
  DOT_MATRIX_ESC_P2 = 'DOT_MATRIX_ESC_P2',
  PIUTANG_LEDGER = 'PIUTANG_LEDGER',
  FAST_PIN_SWITCH = 'FAST_PIN_SWITCH',
  SHIFT_RECONCILIATION = 'SHIFT_RECONCILIATION',
  COGS_PRIVACY_MASK = 'COGS_PRIVACY_MASK',

  // Enterprise & Multi-Location (Enterprise Tier)
  REALTIME_SYNC = 'REALTIME_SYNC',
  MULTI_WAREHOUSE = 'MULTI_WAREHOUSE',
  SUPPLIER_RETURNS = 'SUPPLIER_RETURNS',
  MARKETPLACE_SYNC = 'MARKETPLACE_SYNC',
  WHATSAPP_OFFICIAL_CLOUD = 'WHATSAPP_OFFICIAL_CLOUD',

  // Deferred Operational Backlog
  MINIMARKET_FAST_SCAN = 'MINIMARKET_FAST_SCAN',
  RESTO_TABLE_MANAGEMENT = 'RESTO_TABLE_MANAGEMENT',
}
