/**
 * Sales Order and PayLink Payment Statuses
 */
export enum OrderPaymentStatus {
  UNPAID = 'UNPAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  EXPIRED = 'EXPIRED',
  VOIDED = 'VOIDED',
  REFUNDED = 'REFUNDED',
}

export enum OrderFulfillmentStatus {
  PENDING_ALLOCATION = 'PENDING_ALLOCATION',
  ALLOCATED_FIFO = 'ALLOCATED_FIFO',
  SURAT_JALAN_ISSUED = 'SURAT_JALAN_ISSUED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethodType {
  CASH = 'CASH',
  PAYLINK_QRIS = 'PAYLINK_QRIS',
  PAYLINK_VA = 'PAYLINK_VA',
  PAYLINK_EWALLET = 'PAYLINK_EWALLET',
  PAYLINK_CARD = 'PAYLINK_CARD',
  KASBON_CREDIT = 'KASBON_CREDIT',
  BANK_TRANSFER_MANUAL = 'BANK_TRANSFER_MANUAL',
}
